# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce2cd4d0dc356d3748ca466ea6991f87aea4900ce1632d7aadcd527a18af67fa523f88f50c0436ca4c3227ab9fe8454ac315dc48bda2c0d6b21536ed6632e8ef

test:
  secret_key_base: cd33922a6b8530564d1c8daf11bfc84419921bede03bfa4fc45629d968746cb8476f6a04f995a601b4db4c5f3024f08a4cbd4daf5c120b12154aa6c993b453b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
